version: '3'
services:
  npm:
    build:
      context: .
    network_mode: 'host'
    environment:
      # application-specific environment variables
      TIMESHEET_DIR:
    volumes:
      - .:/project
    working_dir: /project
    entrypoint: npm
