version: '3'
services:
  npm:
    build:
      context: .
    network_mode: 'host'
    environment:
      # application-specific environment variables
      TIMESHEET_DIR:
    volumes:
      - .:/project
      - ${TIMESHEET_DIR}:${TIMESHEET_DIR}
    working_dir: /project
    entrypoint: npm
